### ISSUE TITLE
Error starting Uvicorn

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/larkm#13]
Line 41 of larkm.py

Possible issue with authorization header? maybe fastapi, maybe something else?

```
$ python3 -m uvicorn larkm:app
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/bweigel/.local/lib/python3.9/site-packages/uvicorn/__main__.py", line 4, in <module>
    uvicorn.main()
  File "/home/bweigel/.local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/bweigel/.local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/bweigel/.local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bweigel/.local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/bweigel/.local/lib/python3.9/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/bweigel/.local/lib/python3.9/site-packages/uvicorn/main.py", line 577, in run
    server.run()
  File "/home/bweigel/.local/lib/python3.9/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/bweigel/.local/lib/python3.9/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/bweigel/.local/lib/python3.9/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/bweigel/.local/lib/python3.9/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/bweigel/.local/lib/python3.9/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/html/larkm.py", line 46, in <module>
    authorization: Annotated[str | None, Header()] = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by mjordan** [comment]
Need to test this on Red Hat Enterprise Linux release 8.6 and higher.

**Comment by mjordan** [comment]
Testing this now on rockylinux 8.10 (as a docker container) and larkm starts up with no issue.

**Comment by mjordan** [comment]
@bondjimbond at your convenience can you test this again?
